on:
  workflow_dispatch:
  release:
    types: [published]

name: on-commit-to-main

jobs:
  create-pull-requests:
    uses: ./.github/workflows/reusable-workflow.yaml
    secrets: inherit
    with:
      repository_name: "felipempda/test-reference-image"
      repository_branch: "main"
      files_to_update: "dev/deployment.yaml qa/deployment.yaml prod/deployment.yaml"
      sed_image_ref: "lza-config-validator"