on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Docker Image]
    branches: [main]
    types: 
      - completed

name: Create Pull Request to update tag references

jobs:
  create-pull-request:
    uses: ./.github/workflows/reusable-workflow.yaml
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    secrets: inherit
    with:
      repository_name: "felipempda/test-reference-image"
      repository_branch: "main"
      files_to_update: "dev/deployment.yaml qa/deployment.yaml prod/deployment.yaml"
      sed_image_ref: "lza-config-validator" 