on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Docker Image]
    branches: ["v?[0-9]+.[0-9]+.[0-9]+"]
    types: [completed]

name: Create Pull Request to update tag references

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context 1 - before
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code clean
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
      - name: Seeing tags
        run: |
          git describe --tags --always --abbrev=0
      - name: Dump GitHub context 1 - after
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"


      - name: Dump GitHub context 2 - before
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code clean
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{github.sha}}
          repository: ${{github.repository}}
      - name: Seeing tags
        run: |
          git describe --tags --always --abbrev=0
      - name: Dump GitHub context 2 - after
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"


      - name: Dump GitHub context 3 - before
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code clean
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{ github.event.workflow_run.head_sha }}
          repository: ${{github.event.workflow_run.head_repository.full_name }}
      - name: Seeing tags
        run: |
          git describe --tags --always --abbrev=0
      - name: Dump GitHub context 3 - after
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
    
  create-pull-request:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/reusable-workflow.yaml
    # only if it's workflow_run from a sucessfull release or if it's triggered manually
    if: ${{ ((github.event.workflow_run.conclusion == 'success') && (github.event.workflow_run.event == 'release')) || (github.event_name == 'workflow_dispatch') }}
    secrets: 
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    with:
      repository_name: "felipempda/test-reference-image"
      repository_branch: "main"
      files_to_update: "dev/deployment.yaml qa/deployment.yaml prod/deployment.yaml"
      sed_image_ref: "lza-config-validator" 