on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Docker Image]
    # branches: [main] this doesn't work for workflows that run on releases
    types: [completed]

name: Create Pull Request to update tag references

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context 1 - before
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code clean
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
      - name: Seeing tags
        run: |
          git describe --tags --always --abbrev=0
      - name: Dump GitHub context 1 - after
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"


      - name: Dump GitHub context 2 - before
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code clean
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{github.sha}}
          repository: ${{github.repository}}
      - name: Seeing tags
        run: |
          git describe --tags --always --abbrev=0
      - name: Dump GitHub context 2 - after
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"


      - name: Dump GitHub context 3 - before
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code clean
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Seeing tags
        run: |
          git describe --tags --always --abbrev=0
      - name: Dump GitHub context 3 - after
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
  test-multi:
    runs-on: ubuntu-latest
    # run if build workflow is successful or if is requested manually:
    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name = 'workflow_dispatch') }}
    steps:
      - name: Test
        run: echo "yae"

  create-pull-request:
    uses: ./.github/workflows/reusable-workflow.yaml
    if: false # ${{ github.event.workflow_run.conclusion == 'success' }}
    secrets: inherit
    with:
      repository_name: "felipempda/test-reference-image"
      repository_branch: "main"
      files_to_update: "dev/deployment.yaml qa/deployment.yaml prod/deployment.yaml"
      sed_image_ref: "lza-config-validator" 